// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/ukane-philemon/scomp/internal/class"
	"github.com/ukane-philemon/scomp/internal/student"
)

type AuthenticatedAdmin struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	AuthToken string `json:"authToken"`
}

type CompleteClassInfo struct {
	Class    *class.Class       `json:"class"`
	Students []*student.Student `json:"students"`
}

type Mutation struct {
}

type Query struct {
}
